# This workflow will do a clean install of node dependencies, build the source
# code and run tests across different versions of node For more information
# see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Node.js CI

on:
  push:
    branches: [saga]
  pull_request:
    branches: [saga]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 14.15.5

    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.15.5
    # - run: npm ci
    # - run: npm run build --if-present
    # - run: npm test
